# Generated by Django 4.0.1 on 2022-01-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('agentClass', models.CharField(choices=[('CONTROLLER', 'controller'), ('DUELIST', 'duelist'), ('INITIATOR', 'initiator'), ('SENTINEL', 'sentinel')], default='CONTROLLER', max_length=10)),
            ],
        ),
    ]
