# Generated by Django 4.0.1 on 2022-01-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agents',
            new_name='Agent',
        ),
    ]
