# Generated by Django 4.0.1 on 2022-02-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0002_rename_agents_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('xPos', models.IntegerField()),
                ('yPos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('xPos', models.IntegerField()),
                ('yPos', models.IntegerField()),
                ('childPinAmount', models.IntegerField()),
                ('childPinIds', models.JSONField()),
                ('isAttacking', models.BooleanField()),
                ('rating', models.FloatField()),
                ('createdOn', models.DateTimeField(max_length=10)),
                ('author', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('numLineups', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='cAbility',
            field=models.CharField(default='changeme', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='eAbility',
            field=models.CharField(default='changeme', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='qAbility',
            field=models.CharField(default='changeme', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='xAbility',
            field=models.CharField(default='changeme', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='agentClass',
            field=models.CharField(choices=[('CONTROLLER', 'controller'), ('DUELIST', 'duelist'), ('INITIATOR', 'initiator'), ('SENTINEL', 'sentinel')], default='CONTROLLER', max_length=16),
        ),
    ]
