# Generated by Django 4.0.1 on 2022-02-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0003_childlineup_lineup_map_agent_cability_agent_eability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='ability',
            field=models.CharField(default='changeme', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineup',
            name='character',
            field=models.CharField(choices=[('AS', 'Astra'), ('BRE', 'Breach'), ('BRI', 'Brimstone'), ('CH', 'Chamber'), ('CY', 'Cypher'), ('JE', 'Jett'), ('KI', 'Killjoy'), ('KA', 'KAY/O'), ('NE', 'Neon'), ('OM', 'Omen'), ('PH', 'Phoenix'), ('RA', 'Raze'), ('RE', 'Reyna'), ('SA', 'Sage'), ('SK', 'Skye'), ('SO', 'Sova'), ('VI', 'Viper'), ('YO', 'Yoru')], default='changeme', max_length=64),
            preserve_default=False,
        ),
    ]
