# Generated by Django 4.0.1 on 2022-02-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0004_lineup_ability_lineup_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='map',
            field=models.CharField(choices=[('AS', 'Ascent'), ('BI', 'Bind'), ('BR', 'Breeze'), ('FR', 'Fracture'), ('HA', 'Haven'), ('IC', 'Icebox'), ('SP', 'Split')], default='changeme', max_length=16),
            preserve_default=False,
        ),
    ]
