# Generated by Django 4.0.1 on 2022-02-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0005_lineup_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='childlineup',
            name='content',
            field=models.URLField(default='changeme'),
            preserve_default=False,
        ),
    ]
