# Generated by Django 4.0.1 on 2022-04-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0007_alter_childlineup_content_alter_childlineup_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='cAbility',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='eAbility',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='qAbility',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='xAbility',
        ),
        migrations.AddField(
            model_name='agent',
            name='abilities_field',
            field=models.JSONField(default='changeme', verbose_name='[]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lineup',
            name='character',
            field=models.CharField(blank=True, choices=[('Astra', 'Astra'), ('Breach', 'Breach'), ('Brimstone', 'Brimstone'), ('Chamber', 'Chamber'), ('Cypher', 'Cypher'), ('Jett', 'Jett'), ('Killjoy', 'Killjoy'), ('KAY/O', 'Kayo'), ('Neon', 'Neon'), ('Omen', 'Omen'), ('Phoenix', 'Phoenix'), ('Raze', 'Raze'), ('Reyna', 'Reyna'), ('Sage', 'Sage'), ('Skye', 'Skye'), ('Sova', 'Sova'), ('Viper', 'Viper'), ('Yoru', 'Yoru')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='map',
            field=models.CharField(blank=True, choices=[('Ascent', 'Ascent'), ('Bind', 'Bind'), ('Breeze', 'Breeze'), ('Fracture', 'Fracture'), ('Haven', 'Haven'), ('Icebox', 'Icebox'), ('Split', 'Split')], max_length=16, null=True),
        ),
    ]
