# Generated by Django 4.0.1 on 2022-04-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0008_remove_agent_cability_remove_agent_eability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='banner_image',
            field=models.ImageField(default='changeme', upload_to='static/img/champBanners/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='mugshot_image',
            field=models.ImageField(default='changeme', upload_to='static/img/champIcons/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='select_sound',
            field=models.FileField(default='changeme', upload_to='static/sfx/<django.db.models.fields.CharField>/'),
            preserve_default=False,
        ),
    ]
