# Generated by Django 4.0.1 on 2022-04-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0009_agent_banner_image_agent_mugshot_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='abilities_field',
        ),
    ]
