# Generated by Django 4.0.1 on 2022-04-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0010_remove_agent_abilities_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='cAbility',
            field=models.CharField(default='changeme', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='eAbility',
            field=models.CharField(default='changeme', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='qAbility',
            field=models.CharField(default='changeme', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='xAbility',
            field=models.CharField(default='changeme', max_length=30),
            preserve_default=False,
        ),
    ]
