# Generated by Django 4.0.1 on 2022-05-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0012_alter_agent_banner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='numLineups',
            new_name='num_lineups',
        ),
        migrations.AddField(
            model_name='map',
            name='map_image',
            field=models.FileField(default=0, upload_to='img/maps/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='banner_image',
            field=models.FileField(upload_to='img/banners/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mugshot_image',
            field=models.ImageField(blank=True, upload_to='img/icons/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='select_sound',
            field=models.FileField(blank=True, upload_to='sfx/<django.db.models.fields.CharField>/'),
        ),
    ]
